version: '3.8'
services:
  # web:
  #   build:
  #     context: ../rpg-master-webserver
  #     dockerfile: Dockerfile
  #   volumes:
  #   - type: bind
  #     source: ../rpg-master-webserver
  #     target: /rpg-master-webserver
  #   depends_on:
  #     - frontend
  #     - api
  #   ports:
  #   - "80:80"
    # - "443:443"

  frontend:
    image: zaknafain/rpg-master-frontend:1.0.0-SNAPSHOT
    volumes:
    - type: bind
      source: ../rpg-master-frontend
      target: /rpg-master-frontend
    ports:
      - "4200:4200"
    depends_on:
      - api

  api:
    image: zaknafain/rpg-master-api:1.0.1
    volumes:
    - type: bind
      source: ../rpg-master-api
      target: /rpg-master-api
    depends_on:
      - db
    env_file:
    - ../rpg-master-api/.env

  db:
    image: postgres:9.6.18-alpine
    env_file:
    - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
