version: '3.8'
services:
  api:
    image: zaknafain/rpg-master-api:1.0.0
    volumes:
    - type: bind
      source: ../rpg-master-api
      target: /rpg-master-api
    depends_on:
      - db
    env_file:
    - ../rpg-master-api/.env

  db:
    image: postgres:9.6.18-alpine
    env_file:
    - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
