version: '3.7'
services:
  web:
    build:
      context: ../rpg-master-webserver
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ../rpg-master-webserver
      target: /rpg-master-webserver
    depends_on:
      - frontend
      - api
    ports:
    - "80:80"
    # - "443:443"

  frontend:
    build:
      context: ../rpg-master-frontend
      dockerfile: Dockerfile
    command: sh -c "npm install && npm start"
    volumes:
    - type: bind
      source: ../rpg-master-frontend
      target: /rpg-master-frontend
    depends_on:
      - api

  api:
    build:
      context: ../rpg-master-api
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ../rpg-master-api
      target: /rpg-master-api
    depends_on:
      - mysql
    env_file:
    - ../rpg-master-api/.env

  mysql:
    image: mysql:5.7
    # data files live in /var/lib/docker_mysql
    volumes:
      - ./mysql.cnf:/etc/mysql/mysql.conf.d/overwrite.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
